// Code generated by goctl. DO NOT EDIT.
package types

type Connector struct {
	SourceType  string `json:"sourceType"`
	SourceTable string `json:"sourceTable"`
	SourceDB    string `json:"sourceDb"`
	SourceId    string `json:"sourceId"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type ConnectorListResponse struct {
	ConnectorList []*Connector `json:"connectorList"`
	PageAndSize   PageAndSize  `json:"pageAndSize"`
}

type ConnectorModel struct {
	Source Source `json:"source"`
}

type DefaultConfigResponse struct {
	QueryNode string     `json:"queryNode"`
	Shards    [][]string `json:"shards"`
	Cluster   string     `json:"cluster"`
}

type DeleteConnectorRequest struct {
	Type     string `json:"type"`
	SourceId string `json:"sourceId"`
}

type Dm struct {
	ID              int        `json:"id"`
	Name            string     `json:"name"`
	SourceType      string     `json:"sourceType"`
	SourceDsn       string     `json:"sourceDsn"`
	SourceTable     string     `json:"sourceTable"`
	SourceDb        string     `json:"sourceDb"`
	SourceQueryKey  string     `json:"sourceQueryKey"`
	TargetType      string     `json:"targetType"`
	TargetShards    [][]string `json:"targetShards"`
	TargetDB        string     `json:"targetDB"`
	TargetChProxy   string     `json:"targetChProxy"`
	TargetTable     string     `json:"targetTable"`
	WindowStartHour int        `json:"windowStartHour"`
	WindowEndHour   int        `json:"windowEndHour"`
	Status          string     `json:"status"`
	Information     string     `json:"information"`
	CreateTime      string     `json:"createTime"`
	UpdateTime      string     `json:"updateTime"`
}

type DmListResponse struct {
	DmList      []Dm        `json:"dmList"`
	PageAndSize PageAndSize `json:"pageAndSize"`
}

type DmModel struct {
	Source          Source `json:"source"`
	Target          Target `json:"target"`
	WindowStartHour string `json:"windowStartHour"`
	WindowEndHour   string `json:"windowEndHour"`
}

type ExecSqlRequest struct {
	Sql []string `json:"sql"`
}

type ExecSqlResponse struct {
	FailedTables  []string `json:"failedTables"`
	FailedReasons []string `json:"failedReasons"`
}

type GenerateCreateSqlRequest struct {
	Dsn      string   `json:"dsn"`
	Table    []string `json:"table"`
	Database string   `json:"database"`
}

type GenerateCreateSqlResponse struct {
	Sql           []string `json:"sql"`
	QueryKey      []string `json:"queryKey"`
	FailedTables  []string `json:"failedTables"`
	FailedReasons []string `json:"failedReasons"`
}

type InstancesRequest struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type ListRequest struct {
	DbName string `json:"dbName"`
	PageAndSize
}

type PageAndSize struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type Rtu struct {
	ID             int        `json:"id"`
	Name           string     `json:"name"`
	SourceType     string     `json:"sourceType"`
	SourceTopic    string     `json:"sourceTopic"`
	SourceDsn      string     `json:"sourceDsn"`
	SourceTable    string     `json:"sourceTable"`
	SourceDb       string     `json:"sourceDb"`
	SourceQueryKey string     `json:"sourceQueryKey"`
	TargetType     string     `json:"targetType"`
	TargetShards   [][]string `json:"targetShards"`
	TargetDB       string     `json:"targetDB"`
	TargetChProxy  string     `json:"targetChProxy"`
	TargetTable    string     `json:"targetTable"`
	Status         string     `json:"status"`
	Information    string     `json:"information"`
	CreateTime     string     `json:"createTime"`
	UpdateTime     string     `json:"updateTime"`
}

type RtuList struct {
	RtuList     []Rtu       `json:"rtuList"`
	PageAndSize PageAndSize `json:"pageAndSize"`
}

type RtuModel struct {
	Source Source `json:"source"`
	Target Target `json:"target"`
}

type Source struct {
	Dsn            string   `json:"dsn"`
	Tables         []string `json:"tables"`
	Suffix         string   `json:"suffix"`
	SelectedTable  []string `json:"selectedTable"`
	CreateTableSql []string `json:"createTableSql"`
	QueryKey       []string `json:"queryKey"`
}

type String struct {
	String string `json:"string"`
}

type StringList struct {
	StringList []string `json:"stringList"`
}

type Target struct {
	Databases        []string `json:"databases"`
	SelectedDatabase string   `json:"selectedDatabase"`
}

type TokenResponse struct {
	Token string `json:"token"`
}

type UserAddRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	GroupID  int    `json:"groupID"`
}

type UserGetResponse struct {
	Name    string `json:"name"`
	GroupId int    `json:"groupId"`
	Email   string `json:"email"`
}

type UserLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
