version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      TZ: "Asia/Shanghai"
  ch-server-1:
    container_name: ch-server-1
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros1.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-server-2:
    container_name: ch-server-2
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros2.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8124:8123
      - 9001:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-server-3:
    container_name: ch-server-3
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros3.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8125:8123
      - 9002:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-server-4:
    container_name: ch-server-4
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros4.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8126:8123
      - 9003:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-server-5:
    container_name: ch-server-5
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros5.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8127:8123
      - 9004:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-server-6:
    container_name: ch-server-6
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros6.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8128:8123
      - 9005:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-query-server:
    container_name: ch-query-server
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macrosquery.xml:/etc/clickhouse-server/config.d/macros.xml      
    ports:
      - 8129:8123
      - 9006:9000
    environment:
      TZ: "Asia/Shanghai"
  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    environment:
      TZ: "Asia/Shanghai"